export const environment = {
  production: false,
  KPIHeatMapView_URL: './assets/data/PatientKPIHeatMap.json',
  // PatientsList_URL: './assets/data/Patient.json',
  PatientsList_URL: 'https://biapps-dev.fmcna.com/metricsapi/getpatientList',
  // PatientMetric_URL: './assets/data/PatientMetric.json',
  PatientMetric_URL: 'https://biapps-dev.fmcna.com/metricsapi/getmetricList',
  applicationDataApiUrl: 'https://dev-logixml.intranet.fmcna.com/biproductservices/app_data/detailsByAppName?appName=',
  userHierarchyAccessApiUrl: 'https://dev-logixml.intranet.fmcna.com/biproductservices/hierarchy/userHierarchyAccess?userId=',
  summaryApiUrl: 'https://biapps-dev.fmcna.com/metricsapi/getEntityTrendSummary',
  kPICategoryApiUrl: 'https://biapps-dev.fmcna.com/metricsapi/getCategorySummary',
  kPIDetailsApiUrl: 'https://biapps-dev.fmcna.com/metricsapi/getAllKpiData',
  phySingleListApiUrl: 'https://biapps-dev.fmcna.com/metricsapi/getEntitySingleList',
  phyCqsScoreApiUrl: './assets/data/PhyCQSScoreOvertime.json',
  overtimeMonthLabelsApiUrl: './assets/data/OvertimeMonthLabels.json',
  phyCompareHeaders: './assets/data/PhyCompareHeaders.json',
  phyCompareApiUrl: './assets/data/PhyCompareData.json',
  entityCensusApiUrl: 'https://biapps-dev.fmcna.com/metricsapi/apicontroller/entityCensus',
  
  userAccessInfoUrl: 'https://biapps-dev.fmcna.com/metricsapi/authorizationController/userAccessInfo?userId=',
  USER_ID_COOKIE_NAME: 'fmcUserID',
  SSO_LOGIN_URL: 'https://biapps-dev.fmcna.com/cqsphy',
  userHierarchyAccessByUserIdApiUrl: 'https://dev-logixml.intranet.fmcna.com/biproductservices/hierarchy/userHierarchyAccessByUserId',
};
